# Generated by Django 4.2.1 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='rand_header',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='sheet',
            field=models.CharField(default='Sheet1', max_length=20),
            preserve_default=False,
        ),
    ]
