# Generated by Django 4.2.1 on 2023-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_filemodel_rand_header_filemodel_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='rand_header',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='cif_firma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='nume_firma',
            field=models.CharField(default='firma', max_length=100),
            preserve_default=False,
        ),
    ]
