# Generated by Django 4.2.1 on 2023-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_remove_filemodel_rand_header_filemodel_cif_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='rand_header',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
