# Generated by Django 4.2.1 on 2023-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
